### ISSUE TITLE
有關Student.java的queryExamResults()

### ISSUE THREAD

**Issue by jiaoliao** [Max-Projects/OnlineExamServer#10]
在`urls.py`裡面沒有 `queryExamResults()` 所回傳uri `/course/%d/exam/%d/student/%d/score` 的相關程式，導致只能老師查詢某考試所有學生成績，而學生無法查詢成績，是否應該是
`/course/%d/exam/%d/problem/%d/student/%d/score-and-comment` ?

因為在`urls.py`發現以下這一行程式，較為符合

```
57: url(r'^course/(?P<c_id>\d+)/exam/(?P<e_id>\d+)/problem/(?P<p_id>\d+)/student/(?P<s_id>\d+)/score-and-comment$', problem_scoring_and_comment),
```

且發現`urls.py`有重複的部分
![2016-02-22 1 48 43](https://cloud.githubusercontent.com/assets/15962916/13204276/bb776cf8-d906-11e5-89c8-3e095871fab1.png)

**Comment by sc0ttie** [comment]
我把 `score-and-comment` 那隻 API 改了一下，
再麻煩你測試一下有沒有問題吧！

**Comment by jiaoliao** [comment]
`urls.py` 裡面 

```
43： url(r'^course/(?P<c_id>\d+)/exam/(?P<e_id>\d+)/student/(?P<s_id>\d+)/score-and-comment$', exam_scoring_and_comment)
```

`s_id`是設定/d(a number)，但`problem.py`裡

```
142： student = User.objects.get(student_id=s_id)
```

student取得的值是英數(an alphanumeric character)，因為目前student id是採用測試範例使用的`4025s`。

測了兩個方法都測試成功：
1. 將`\d`改成`\w`
2. 將 `student = User.objects.get(student_id=s_id)`，改成`student = User.objects.get(id=s_id)`

我比較喜歡第一種方式，這樣就可以直接輸入student id，而不用去記每一個人的user id，只是這樣還會動到`Student.java`，要把`super.userId`改掉，改成由使用者傳回值，有比較建議哪一個嗎?

**Comment by sc0ttie** [comment]
沒錯，的確是用字串才符合設計理念
