### ISSUE TITLE
Student.java的attendExam(int courseId, int examId)

### ISSUE THREAD

**Issue by jiaoliao** [Max-Projects/OnlineExamServer#11]
一樣有 #10 兩邊不對稱的問題
![2016-02-25 1 44 46](https://cloud.githubusercontent.com/assets/15962916/13295194/a486ba90-db62-11e5-9ebe-d734cbd53040.png)
![2016-02-25 1 47 16](https://cloud.githubusercontent.com/assets/15962916/13295195/a5704994-db62-11e5-92f7-2b0792949b9d.png)

另外，在`exam.py`中
1. 一樣有id取得的問題
2. `record.state`型態問題，在`models.py` `LoggingInUser`class裡 `state`被設定為整數型態，但在`exam.py`中卻是回傳UserState型態，下面是其所顯示的例外處理訊息

> Exception Value: int() argument must be a string, a bytes-like object or a number, not 'UserState'

![2016-02-25 1 59 26](https://cloud.githubusercontent.com/assets/15962916/13295503/2b872e34-db64-11e5-8993-7ccaec54fcfe.png)

**Comment by jiaoliao** [comment]
當學生要參加考試時，Logging in users裡面若有重複登入情形(如下)，
![logginginusers](https://cloud.githubusercontent.com/assets/15962916/13313752/3d66c6ba-dbdb-11e5-8a7e-0228775708ae.png)
出現Exception

```
Exception Type: MultipleObjectsReturned
Exception Value:get() returned more than one LoggingInUser -- it returned 2!
```

但Error Code裡面沒有MultipleObjectsReturned (ps. 已在自己本機新增)

**Comment by sc0ttie** [comment]
`UserState` 的問題應該解決了，
現在它變成 `IntEnum`。

至於重複登入的部分，
我在使用者登入的時候清空 `LoggingInUser`，
在參加考試就不會出錯了。
