### ISSUE TITLE
關於exam的資料表

### ISSUE THREAD

**Issue by Rita94105** [Max-Projects/OnlineExamServer#12]
學姊
1. 我不太了解exam裡面的modify time是什麼意思
2. 還有之前有設計可以選擇多久擷取一次畫面
   但是資料表裡面好像沒有擷取畫面的時間

**Comment by i-MaxYuan** [comment]
1. modify time 是修改當時的時間戳記
2. 設計中並沒有考慮擷取畫面的時間，你們自己加上
