### ISSUE TITLE
交卷狀況

### ISSUE THREAD

**Issue by i-MaxYuan** [Max-Projects/OnlineExamServer#2]
考試過程中，老師如何知道學生交卷狀況
有哪些學生已交卷，我們需要在老師介面上顯示學生交卷狀況

**Comment by sc0ttie** [comment]
我傾向的方式是當學生 submit source code 的時候，
server 利用 socket 通知老師有學生交卷，(fire event)
介面再反映出來。

**Comment by i-MaxYuan** [comment]
event中傳回的是單一學生，還是多個學生，會記錄交卷時間嗎，有交卷時間可以標示先後次序

**Comment by ChouYiLi** [comment]
什麼是fire event?
我需要知道交卷時server通知老師的訊息為何
這樣老師端取得訊息時才知道是不是學生交卷，介面該做反應

**Comment by ChouYiLi** [comment]
source code檔案名稱，交卷時間，老師及學生測資分別的執行狀況

**Comment by i-MaxYuan** [comment]
這是指event中會有的資訊嗎？
