### ISSUE TITLE
Student-sendTestResult()

### ISSUE THREAD

**Issue by ChouYiLi** [Max-Projects/OnlineExamServer#4]
sendTestResult的參數String result是指執行後結果，還是交卷的程式碼
每個學生考試中若沒有執行過自己的程式碼，就不會有執行結果

**Comment by ChouYiLi** [comment]
老師閱卷時可看見學生是否已先執行過測資，並知道執行後有無Error

**Comment by sc0ttie** [comment]
看不太懂到底是問了哪些問題，我就猜猜樂自己分了三點：
1. `result` 是學生執行過後的結果，並非程式碼（上傳程式碼的 API 是在 [`.submitSourceCode()`](https://github.com/Max-Projects/OnlineExamServer/blob/master/OnlineExamSystemAPI/src/org/mislab/api/Student.java#L20-L31) 這邊）
2. 當然，如果學生沒有呼叫 `.sendTestResult()`，那麼老師在閱卷的時候就只會拿到空字串
3. 看你們怎麼決定何時呼叫 `.sendTestResult()`，是額外做一個按鈕讓學生上傳結果，或是每次學生執行都上傳。而老師在閱卷時所看到的就只是學生執行過後的結果，並不會顯示他到底對不對，這必須讓老師自己判斷，亦或是你們在顯示的時候自己去抓答案做 diff 再給老師看。

**Comment by ChouYiLi** [comment]
喔～
那學生交卷傳送程式碼是哪個method

**Comment by i-MaxYuan** [comment]
ChouYiLi
notifications@github.com>於 2015年12月23日 週三，下午10:10寫道：
儀齡的回應有妳的答案，要仔細看
