### ISSUE TITLE
範例測試檔出現錯誤訊息

### ISSUE THREAD

**Issue by jiaoliao** [Max-Projects/OnlineExamServer#5]
編譯測試檔後並執行，可成功連線且可新增資料(web上有更新)。
但執行第一次時，出現：
![2016-01-20 11 58 50](https://cloud.githubusercontent.com/assets/15962916/12439712/c1478af2-bf6e-11e5-9d77-df5769c8f364.png)

而後更改測試檔內容，欲新增第二筆資料，執行後出現：
![2016-01-20 12 01 31](https://cloud.githubusercontent.com/assets/15962916/12439731/f0ebe56e-bf6e-11e5-8f3b-27ac20a09966.png)

不過若是第一次就新增學生，不會出現Class Cast Exception，但第二次一樣會出現Json Syntax Exception。

**Comment by i-MaxYuan** [comment]
試著是否可以將錯誤行移除再執行，程式是否正確？
同時也要檢查資料庫的正確性！
