### ISSUE TITLE
查詢學生以及學生參加考試測試問題

### ISSUE THREAD

**Issue by Rita94105** [Max-Projects/OnlineExamServer#6]
在新增完考試之後
查詢該課程學生
（學姐本來測試程式裡寫好的queryCourseStudents(int cid)）
及學生登入參加考試
（自己寫了一個attendExam()）
但都出現了感覺很類似的ERROR
不知道為什麼會這樣...
queryCourseStudentsErr
![querycoursestudentserr](https://cloud.githubusercontent.com/assets/15962130/13070398/309d86dc-d4c7-11e5-9095-03db4a1497cd.png)
attendExamErr
![attenderr_1](https://cloud.githubusercontent.com/assets/15962130/13070346/c60bc9e6-d4c6-11e5-93fd-84781f0b0962.png)
![attenderr_2](https://cloud.githubusercontent.com/assets/15962130/13070347/c61138a4-d4c6-11e5-8a48-8c8972dd1787.png)

**Comment by i-MaxYuan** [comment]
儀齡初步的判斷是系統在server端就出錯，導致server產生了一些錯誤訊息，這些錯誤訊息當然不是json格式，因此產生這些錯誤！

建議處理方式如下：
1. 在server端將這些錯誤訊息印出
2. 提供完整程式碼，只有這些hardcopy，太少了
3. 在org.mislab.api.Utils.java中，第35行

```
        JsonObject json = gson.fromJson(r.body().string(), JsonObject.class);
```

中的 **r.body().string()** 就是server傳回的訊息，將其內容在傳回前印出，就知道server傳回的錯誤是啥！

**Comment by Rita94105** [comment]
`test.loginTeacher();
 test.queryCourseStudents(2);
 test.logout();`
r.body().string()傳回的是
{"content":{"userId":1,"role":"teacher"},"errorCode":0}

真的是server的問題耶
因為我現在連login再logout也沒有辦法了
可是我也不知道我到底是動到什麼（汗）

**Comment by i-MaxYuan** [comment]
先不要做登出的動作

**Comment by sc0ttie** [comment]
依我看目前的問題是出在 `queryCourseStudents()`
但是 `{"content":{"userId":1,"role":"teacher"},"errorCode":0}` 這個 json 是 `loginTeacher()` 的回傳值
上圖噴出的 `JsonSyntaxException` 是 gson 沒辦法轉換回傳值造成的
因此你應該要找到 server 回傳的非 json 字串才是導致錯誤的主因
進而分析那個字串是哪邊引起
我們才有辦法幫你找出問題

另外假如一開始你可以正常執行登入登出
那就代表 server 沒有問題
應該是資料庫出錯
可能是你呼叫 API 的順序在預期以外讓資料錯亂（隨意舉例像是沒登入卻執行登出、多次重複登入等等）
也可以說是當初設計沒有考慮到這種亂呼叫的情況

檢查看看 LoggingInUser 這張 table
印象中只要沒有使用者在線上則他應該要為空

**Comment by Rita94105** [comment]
學姐
我目前是連老師或者是學生都登不進去了
可是我之前每次執行程式碼都有Login(),Logout()的說
我目前是一行一行執行
現在是卡在55就沒辦法繼續下去了
我的LoggingInUser 這張 table很精彩耶
很多USER我也不知道為什麼
哈哈
是不是因為這個原因阿？？
![err_1](https://cloud.githubusercontent.com/assets/15962130/13133592/a4c326f4-d637-11e5-952b-465066d79221.png)
![logginginuser table](https://cloud.githubusercontent.com/assets/15962130/13133622/e9ce5b9c-d637-11e5-9dc4-51c5e877964c.png)

**Comment by Rita94105** [comment]
學姊
我是因為之前在測試attendExam的時候有error都沒有執行到logout()
所以灌爆了那個table
重新建立資料庫後就解決了server的問題
但是現在學生還是沒有辦法參加考試
