### ISSUE TITLE
submitSourceCode與sendTestResult的不同

### ISSUE THREAD

**Issue by ChouYiLi** [Max-Projects/OnlineExamServer#8]
submitSourceCode與sendTestResult的差別在哪裡？
是否都是交卷功能？

**Comment by sc0ttie** [comment]
`submitSourceCode()` 是送出學生撰寫的程式碼，
`sendTestResult()` 則是測試該程式碼的結果。

其實只是把交卷動作切成兩個 API，
呼叫的時候應該會成對出現。
