### ISSUE TITLE
UnknownState ErrorCode

### ISSUE THREAD

**Issue by ChouYiLi** [Max-Projects/OnlineExamServer#9]
在做老師評分、查詢考試問題內容以及學生加入考試、更改密碼時，都出現了相同的錯誤
都是於登入後，直接進行這些功能
也確定沒有重複登入等狀況
不知道是測試程式寫錯還是系統的關係?!
![scoreandcomment_code](https://cloud.githubusercontent.com/assets/15901299/13164717/7600a10a-d6f2-11e5-82c4-bd5a43401318.jpg)
![scoreandcomment_error](https://cloud.githubusercontent.com/assets/15901299/13164718/777734b8-d6f2-11e5-811a-e42ede58b89d.jpg)
這是老師評分的程式碼及執行結果

![queryprblem_error](https://cloud.githubusercontent.com/assets/15901299/13164738/979be522-d6f2-11e5-8b50-a746f4164ae6.jpg)
![queryprblem_code](https://cloud.githubusercontent.com/assets/15901299/13164739/988ab7d8-d6f2-11e5-8b62-6ec7d0f4d7a2.jpg)
老師查詢考試問題內容

![attendexam_code](https://cloud.githubusercontent.com/assets/15901299/13164754/afdfb7e4-d6f2-11e5-806f-95c530104ab5.jpg)
![attendexam_error](https://cloud.githubusercontent.com/assets/15901299/13164755/b1166dc4-d6f2-11e5-9957-f869b9a70a69.jpg)
學生加入考試

![resetpassword_code](https://cloud.githubusercontent.com/assets/15901299/13164766/bfc18020-d6f2-11e5-94dc-9308761747c7.jpg)
![resetpassword_error](https://cloud.githubusercontent.com/assets/15901299/13164767/c0e6052a-d6f2-11e5-9a79-eb1470186a48.jpg)
學生更改密碼

**Comment by jiaoliao** [comment]
我發現如果在Utils的sendRequest中，使用

> System.out.println(r.body().string());

印出內容的話，就會出現 java.lang.IllegalStateException: closed，

但若是用 

> System.out.println(json);

或

> System.out.println(response.getContent);

就沒上面那個問題了

**Comment by jiaoliao** [comment]
另外，
我將資料庫重置後，跟意立一樣，沒有呼叫在預期以外的指令，
仍然在 查詢問題、評分等API測試中，出現
![2016-02-20 3 13 43](https://cloud.githubusercontent.com/assets/15962916/13186474/64e3b3fa-d781-11e5-965f-2074a5f3c9ef.png)
且發現伺服器出現代碼 500 internal server error的錯誤訊息
![2016-02-20 3 09 25](https://cloud.githubusercontent.com/assets/15962916/13186545/a2e3596c-d781-11e5-80af-bc7ee055622f.png)

附上程式

```
public class Test {
    private Teacher teacher;

    public void loginTeacher() {
        Response res = User.login("teacher", "teacher");

        if (res.success()) {
            teacher = (Teacher) res.getContent().get("user");
        }
    }

    public void logout() {
        if (teacher != null) {
            teacher.logout();
            teacher = null;
        }
    }

    public void queryProblems() {
        output(teacher.queryProblems(1, 1));
    }

    public static void main(String[] args) {
        Test test = new Test();
        test.loginTeacher();
        test.queryProblems();
        test.logout();
    }
}
```

(註冊、登入、建立課程、建立考試、建立問題等程式是使用wiki裡提供的測試範例)

**Comment by sc0ttie** [comment]
我對 `52.192.15.18` 這台伺服器呼叫 @jiaoliao 提供的 `queryProblems()`，
回傳結果為 `{"errorCode": 9}`，
也就是 `ExamNotFound`，
並沒有碰到上述所說的情況，
請你們檢查一下是不是漏了什麼。

另外關於 `sendRequest()` 中印出回傳結果的地方，
應該要先用一個變數把 `r.body().string()` 接起來，
像是：

```
String res = r.body().string();
System.out.format("[%s]\n", res);
JsonObject json = gson.fromJson(res, JsonObject.class);
```

我用關鍵字 `illegalstateexception okhttp` 或是 `illegalstateexception closed` 去查，
第一個出現的結果應該就能解釋為什麼了：https://github.com/square/okhttp/issues/1240

**Comment by jiaoliao** [comment]
那個錯誤是已經在基本情況下(裡面已有一名老師、一名學生、一個課程、一個考試、一個問題)，做查詢動作出現會發生錯誤。
剛剛照上面用個變數把`r.body().string()`放在裡面，結果查詢課程問題時，印出一堆html的內容，放到網頁上一看，顯示以下畫面
![2016-02-21 11 54 17](https://cloud.githubusercontent.com/assets/15962916/13200768/fb66921e-d891-11e5-8379-e1a7902eb7ce.png)
